# Test against this version(s) of Node.js / iojs
environment:
  matrix:
  # node.js
    - nodejs_version: "12"

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm\node_modules -> package.json'    # global npm modules
  - '%APPDATA%\npm-cache -> package.json'           # npm cache
  - 'node_modules -> package.json'                  # local npm modules

hosts:
  localhost: 127.0.0.1

# Install scripts. (runs after repo cloning)
install:
  - npm -g install npm@6
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
